name = "project"
main = "src/index.ts"
compatibility_date = "2023-11-21"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
subscriptionId = "d84973e8-c64e-42f3-aae5-52a21870d1fe"
resourceGroupName = "TEST_RESOURCE_GROUP"
tenantId = "3498a534-71d0-447b-bde9-44fc395828d2"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
[[durable_objects.bindings]]
name = "STORAGE_DO"
class_name = "StorageDO"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
[[migrations]]
tag = "v1"
new_classes = ["StorageDO"]
